# This pipeline deploys code to Maven repo
# push file to Git and pull it from from Jenkins 

pipeline {
  agent any
  
  stages {
    stage ('Compile Stage') {
      steps { 
        withMaven(maven : 'maven_3_5_0') {
            sh 'mvn clean compile' 
        }
      }
    }
    
    stage ('Testing Stage') {
      steps { 
        withMaven(maven : 'maven_3_5_0') {
            sh 'mvn test' 
        }
      }
    } 
    
    stage ('Deployment Stage') {
      steps { 
        withMaven(maven : 'maven_3_5_0') {
            sh 'mvn deploy' 
        }
      }
    }
    
    }
    }
